//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheatreMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actor
    {
        public int Actor_id { get; set; }
        public string Name_actor { get; set; }
        public string Surname_actor { get; set; }
        public string Exposition { get; set; }
        public byte[] Foto { get; set; }
    
        public virtual Actor Actors1 { get; set; }
        public virtual Actor Actor1 { get; set; }
    }
}
