//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheatreMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Place
    {
        public int Place_id { get; set; }
        public int Type_t { get; set; }
        public int Line { get; set; }
        public Nullable<int> Number { get; set; }
        public int Scenne { get; set; }
    }
}
