//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheatreMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public int Price_id { get; set; }
        public Nullable<int> Spectacle_ID { get; set; }
        public Nullable<int> Type_Price { get; set; }
        public Nullable<int> Price1 { get; set; }
    }
}
