//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheatreMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spectacle
    {
        public int Spectacle_id { get; set; }
        public string Spectacle_name { get; set; }
        public string Exposition_sp { get; set; }
        public System.DateTime Date_sp { get; set; }
        public int Actor1 { get; set; }
        public int Actor2 { get; set; }
        public int Actor3 { get; set; }
        public int Actor4 { get; set; }
        public int Actor5 { get; set; }
        public int Actor6 { get; set; }
        public int Actor7 { get; set; }
        public int Actor8 { get; set; }
        public int Actor9 { get; set; }
        public int Actor10 { get; set; }
    }
}
