//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheatreMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int Ticket_id { get; set; }
        public Nullable<int> User_id { get; set; }
        public Nullable<int> Spectacle_id { get; set; }
        public Nullable<int> Place_id { get; set; }
        public Nullable<bool> State { get; set; }
        public int Price_ticket { get; set; }
    }
}
